### ISSUE TITLE
iOS/Mobile 

### ISSUE THREAD

**Issue by davidpike7** [mharris717/ember-drag-drop#3]
Would also be great if this worked on mobile.

Perhaps using the [Draggabilly](http://draggabilly.desandro.com/) library?

**Comment by pedrokiefer** [comment]
+1 for iOS / Mobile support. Time permitting I'll look at what is missing and try to create a patch for it.

**Comment by daniel-de-wit** [comment]
I used this shim which does the job: https://github.com/timruffles/ios-html5-drag-drop-shim

**Comment by granger44** [comment]
Can you elaborate on how you used the shim.  I'm not finding luck with the bare help provided by the shim project; granted, my web dev chops are still fairly low.  Thanks!

**Comment by jordpo** [comment]
@daniel-de-wit thanks for the shim reference. did you get it working with using the sortable-objects component?

**Comment by daniel-de-wit** [comment]
@jordpo It has been a while since I last used this add-on and thus can't remember if it worked. Sorry and good luck.

**Comment by dirkdirk** [comment]
Any progress on mobile functionality?

@daniel-de-wit Do you remember how you imported the `ios-html5-drag-drop-shim` into your Ember app?

**Comment by daniel-de-wit** [comment]
@dirkdirk I'm sorry I don't remember, been a long time :)

**Comment by veelci** [comment]
@dirkdirk I managed to get the polyfill added to my ember project via an [addon](
https://github.com/aboveproperty/ember-drag-drop-polyfill), but there is some extra integration work necessary since the polyfill is expecting dragEnter events to be prevented to determine droppable areas.  Otherwise, the polyfill dispatches events to the body.

For the sortable component, it is pretty easy to add:
 ```javascript
  // addon/components/sortable-objects.js
  dragEnter: function() {
    //also needed so drop event will fire
    return false;
  },
```
A similar change would need to be made to to get the draggable-object-target working.
