### ISSUE TITLE
Would it make sense to integrate the sorting functionality into the draggable-object-target?

### ISSUE THREAD

**Issue by remkoboschker** [mharris717/ember-drag-drop#39]
I have a page with multiple targets containing lists of objects that need to be sorted. The page would be simplified if I could define the target as a sortable list or the other way around a sortable list as a target. I think it might reduce some complexity as well. 

I would like to implement the drag-between-sortable-containers feature, but there is an outstanding pull request and I'm not sure what the status is of that. Any guidance would be appreciated.

**Comment by dgavey** [comment]
I believe the outstanding pull request might handle this.  It's a large change and I need to find time to go through it and make some new tests, as well the PR has broken some of the tests.  I hope to get it out in the next few weeks though.

**Comment by remkoboschker** [comment]
Does your comment mean that you do not think it would make sense to merge the `draggable-object-target` and `sortable-objects` components? I understand there are other issues involved such as backward compatibility, time constraints and the like. I'll try the pull request and have a look at the broken tests.

**Comment by dgavey** [comment]
I like the idea of trying to merge them, we would have to leave the sortable-objects for backward compatibility.

**Comment by remkoboschker** [comment]
@Bushjumper do you see any objections to merging the `draggable-objects-target` and the `sortable-objects`? For instance in your nested book scenario? Perhaps we could work on merging #34 and work from there?

**Comment by remkoboschker** [comment]
What should the api look like? Below I've tried to merge what is there.

````
{{#draggable-object-target 
  amount="5"
  sortableObjectList=sortableObjectList
  enableSort=true
  action="increaseRating"
  dragOverAction='myOverAction'
  dragOutAction='myDragOutAction'
  sortEndAction='sortEndAction'
}}
 {{#each sortableObjectList as |item|}}
    {{#draggable-object
      content=item
      isSortable=true
    }}
      {{item.name}}
    {{/draggable-object}}
  {{/each}}
{{/draggable-object-target}}
````
Perhaps we could simplify
````
{{#draggable-object-target 
  amount='5'
  list=(readonly collection)
  action='increaseRating'
  updateList='updateCollectionAction'
  dragOverAction='myOverAction'
  dragOutAction='myDragOutAction'
  as |items|
}}
 {{#each items as |item|}}
    {{#draggable-object content=item}}
      {{item.name}}
    {{/draggable-object}}
  {{/each}}
{{/draggable-object-target}}
````
If the `sortableObjectList` contains items, then `enableSort` is true. 

Sorting actions can be performed on in the drop action `action`.

 I would like to follow the data-down-actions-up pattern in that the collection is updated by the `updateList` action only. The current state of the list would be passed to the `updateList` action. On receiving an updated collection it will be copied an serve as input to the `{{each}}`. This is also the reason for scoping the items the the `{{dragable-object-target}}` component and not passing the collection to it.

Is `isSortable` required on the draggable object or can it be inferred or simply alwas be true? It seems a bit odd that item is set and the `draggable-object` and is used inside the object as well. Perhaps another block-scope would make sense. I'm unsure what is passed around exactly. Are the models or are the components, or both?

Would you like to extract a mixin for {{draggable-object}}? I think an component can always simply be extended as long as there is no template to copy. You can avoid the extra `ember-view` that way (and not break the css framework).

I'm just giving it a try. I understand we need to be backward-compatible and not change too much at once.

**Comment by dgavey** [comment]
The simplified template looks good. I wasn't aware we could use the 'as items' when invoking a wrappable component. How does it know what  collection is used for items?

I can't remember off hand why I used the isSortable=true. I think it was because I couldn't figure out a good way to differentiate that the drag action was in regards to a sortable list and not just a droppable area. I can think of a few ways around that now. I wouldn't mind keeping it as an option though so people could disable certain items in a list from being sortable.

Biggest change here will be the DDAU stuff.  That's a pretty big breaking change, I understand the reason for it, but it will be a painful upgrade for some. 

One problem with only sending up a modified cloned array, is that if we aren't using the cloned array in the render area (and right now people are setting up their own each for that) is that after we hover over another element the swap happens immediately. Then Ember smartly re-renders the each and it looks great.  Only at the drop does the action that a swap happened is sent up.

I looks like you might have come up with a way around that though.  The question being do people need the action sent on drag over, or only on drop? Both/either?

I'm certainly not opposed to the mixin at all.  I see the benefits of it.  We should probably keep the {{draggable-object}} for those who might not have a component ready though. 

One other concern that we should potentially consider, is some people want to be able to drop items from another list into another one, we don't need to do that right away, but if we lay the ground work so that would have the potential of working, that would be good.  The other things to keep in mind that keeps being requested, is the ability to sort both a horizontal and vertical list (currently only fully works with vertical ones) and to fully support having multiple lists on the same page (that one mostly works now I think)

**Comment by remkoboschker** [comment]
You can pass 'as items' in the `{{yield items}}`. 

My idea would be to use the cloned array in the render area. So not `collection`, but its immutable copy `items`.  Would this not make dropping an item in another list easier?

My current use of drag-and-drop gets a bit hard to debug because I have multiple lists on the page that are based on a computed property that does some filtering and a group-by. I suppose it does not really matter as I can always decouple in the component wrapping the drop-target.

For my use-cases I only need an action on the drop. I'm not sure what the drag-over and out could be used for.

What are the currently known issues with dropping an item form one list into another? I have tried out  #34 and it appears to be working well. As far as I can see, they use the drag-coordinator service to hold the state of all the lists on the page in an object containing all  item arrays keyed by a category name. Would that be the best approach according to you?

What are the issues with horizontal sorting? Does it involve a coordinate with two variables? Or is it a matter of the right layout?
